

stages:
    - build
    - test
    - release
    - deploy

variables:
    WORKDIR: /go/src/gitlab.com/hokiegeek.net/teadb

cache:
  paths:
    - teadbd/teadbd

.prep-go-build: &prep-go-build
  before_script:
    - mkdir -p /go/src/gitlab.com/hokiegeek.net/teadb
    - cp -r . /go/src/gitlab.com/hokiegeek.net/teadb
    - apk add --update git
    - go get -d -v ./...

build:
  <<: *prep-go-build
  stage: build
  script:
    - cd teadbd && go build -v ./...

unit-test:
  <<: *prep-go-build
  stage: test
  script:
    - go test -v -cover ./...

## Create container
.build-docker-image: &build-docker-image
  stage: release
  image: docker:git
  services:
    - docker:dind
  script:
    - ls -l teadbd
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  retry: 1

create-container-dev:
  <<: *build-docker-image
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:SNAPSHOT
  except:
    - tags
    - master

create-container:
  <<: *build-docker-image
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  after_script:
    - docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_LATEST_TAG
  only:
    - tags
  except:
    - branches

.server-connector-template: &server-connector-template
  image: alpine:latest
  before_script:
    - apk add --update --no-cache openssh
    - echo $HOST_SSH_KEY | base64 -d > /tmp/sshkey
      # - echo $HOST_SSH_KEY | sed -e 's/ /\n/g' | sed -r -e '1,4{:a;N;4!ba;s/\n/ /g}' | sed -r -e '/^-{5}END/,${:z;N;$!bz;s/\n/ /g}' > /tmp/sshkey
    - chmod 0600 /tmp/sshkey

add-proxy-server:
  <<: *server-connector-template
  stage: deploy
  variables:
      conf_file: proxy-teadb.conf
  script:
    - scp -i /tmp/sshkey -o StrictHostKeyChecking=no ./prod-conf/${conf_file} $ADMIN_USER@${DEPLOY_HOST}:/tmp
    - ssh -i /tmp/sshkey -o StrictHostKeyChecking=no $ADMIN_USER@${DEPLOY_HOST} "sudo mv /tmp/${conf_file} /etc/nginx/conf.d && sudo systemctl restart hgproxy.service"
      # - ssh -i /tmp/sshkey -o StrictHostKeyChecking=no $ADMIN_USER@${DEPLOY_HOST} "sudo mv /tmp/${conf_file} /etc/hgproxy"
      # - ssh -i /tmp/sshkey -o StrictHostKeyChecking=no $ADMIN_USER@${DEPLOY_HOST} "sudo systemctl restart hgproxy.service"

## Service restarter
.service-restarter: &service-restarter
  <<: *server-connector-template
  stage: deploy
  script:
    - scp -i /tmp/sshkey -o StrictHostKeyChecking=no ./prod-conf/${SERVICE} $ADMIN_USER@${DEPLOY_HOST}:/tmp
    - ssh -i /tmp/sshkey -o StrictHostKeyChecking=no $ADMIN_USER@${DEPLOY_HOST} "sudo mv /tmp/${SERVICE} /etc/systemd/system/ && sudo systemctl daemon-reload"
    - ssh -i /tmp/sshkey -o StrictHostKeyChecking=no $ADMIN_USER@${DEPLOY_HOST} "sudo systemctl enable ${SERVICE}; sudo systemctl restart ${SERVICE}"
  retry: 1

restart-service:
  <<: *service-restarter
  variables:
    SERVICE: hgteadb.service
  environment:
    name: production
    url: http://tea.hokiegeek.net
  only:
    - tags
  except:
    - branches
